DriveWheelConfigurationValue:
  type: object
  documentation:
    en: A value indicating which roadwheels will receive torque.
  inherit: QualitativeValue
  properties:
    FrontWheelDriveConfiguration:
      type: schema:DriveWheelConfigurationValue
      documentation:
        en: Front-wheel drive is a transmission layout where the engine drives the front
          wheels.
    FourWheelDriveConfiguration:
      type: schema:DriveWheelConfigurationValue
      documentation:
        en: Four-wheel drive is a transmission layout where the engine primarily drives
          two wheels with a part-time four-wheel drive capability.
    AllWheelDriveConfiguration:
      type: schema:DriveWheelConfigurationValue
      documentation:
        en: All-wheel Drive is a transmission layout where the engine drives all four
          wheels.
    RearWheelDriveConfiguration:
      type: schema:DriveWheelConfigurationValue
      documentation:
        en: Real-wheel drive is a transmission layout where the engine drives the rear
          wheels.
